services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
